### ISSUE TITLE
Examples out of date?

### ISSUE THREAD

**Issue by edevil** [go-kit/go-kit.github.io#17]
I'm trying to follow the tutorials, specifically https://github.com/go-kit/go-kit.github.io/blob/source/_src/examples/stringsvc.md, and it refers stuff that seems to have been changed.

For example, metrics.TimeHistogram does not seem to exist anymore.

**Comment by faeinthebay** [comment]
I just tried to follow the stringsvc tutorial and found many discrepancies when compared to the example files it links to.  

- The tutorial makes references to makeUppercaseProxy() but never defines it, so the user must copy it from the completed example to have their version of the project compile
- The tutorial doesn't differentiate between structs it's showing for illustration and structs the user must create on their own.  I had many compile errors until I realized I wasn't supposed to create a Endpoint and Middleware struct
- The completed examples and code instructions seem to ignore the transport logging section of the tutorial.  The tutorial does not specify that the user shouldn't type that section, which caused compile errors since there was both a loggingMiddleware struct and function.
